using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; // Include for validation attributes

namespace Dento_Clinic.Models.Entity
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    //     This code was generated from a template. 
    //     Manual changes to this file may cause unexpected behavior in your application. 
    //     Manual changes to this file will be overwritten if the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }

        public int PatientId { get; set; }

        // Name validation
        [Required(ErrorMessage = "*Name is required.")]
        [StringLength(100, ErrorMessage = "*Name can't be longer than 100 characters.")]
        public string Name { get; set; }

        // Email validation
        [Required(ErrorMessage = "*Email is required.")]
        [EmailAddress(ErrorMessage = "*Please enter a valid email address.")]
        public string Email { get; set; }

        // Phone validation
        [Required(ErrorMessage = "*Phone number is required.")]
        [Phone(ErrorMessage = "*Please enter a valid phone number.")]
        public string Phone { get; set; }

        // Address validation
        [Required(ErrorMessage = "*Address is required.")]
        [StringLength(250, ErrorMessage = "*Address can't be longer than 250 characters.")]
        public string Address { get; set; }

        // Date of birth validation
        [Required(ErrorMessage = "*Date of birth is required.")]
        [DataType(DataType.Date, ErrorMessage = "*Please enter a valid date.")]
        public Nullable<System.DateTime> DOB { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
