using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; // Include for validation attributes

namespace Dento_Clinic.Models.Entity
{
    //------------------------------------------------------------------------------ 
    // <auto-generated> 
    //     This code was generated from a template. 
    //     Manual changes to this file may cause unexpected behavior in your application. 
    //     Manual changes to this file will be overwritten if the code is regenerated. 
    // </auto-generated> 
    //------------------------------------------------------------------------------

    public partial class Treatment
    {
        public int TreatmentId { get; set; }

        // AppointmentId can be nullable, so no validation needed here if the relationship is optional
        public Nullable<int> AppointmentId { get; set; }

        // TreatmentDetails validation
        [Required(ErrorMessage = "*Treatment details are required.")]
        [StringLength(500, ErrorMessage = "*Treatment details can't be longer than 500 characters.")]
        public string TreatmentDetails { get; set; }

        // Cost validation
        [Required(ErrorMessage = "*Cost is required.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "*Cost must be greater than 0.")]
        public decimal Cost { get; set; }

        // TreatmentDate validation
        [Required(ErrorMessage = "*Treatment date is required.")]
        public System.DateTime TreatmentDate { get; set; }

        public virtual Appointment Appointment { get; set; }
    }
}
